// Downloads the selected Open Images photographs (CC BY 2.0 as listed by the dataset),
// applies EXIF orientation and writes responsive WebP files plus a typed metadata module.
// Usage: npm run images
import { mkdir, readFile, writeFile, access } from 'node:fs/promises'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const cacheDir = join(root, 'scripts', '.cache')
const outDir = join(root, 'public', 'images')
const widths = [160, 320, 640, 960]
const manifest = JSON.parse(await readFile(join(root, 'scripts', 'images.manifest.json'), 'utf8'))

await mkdir(cacheDir, { recursive: true })
await mkdir(outDir, { recursive: true })

const exists = (p) => access(p).then(() => true, () => false)
const toHex = (n) => Math.round(n).toString(16).padStart(2, '0')
const meta = {}

for (const img of manifest.images) {
  const original = join(cacheDir, `${img.id}.jpg`)
  if (!(await exists(original))) {
    const url = `https://open-images-dataset.s3.amazonaws.com/${img.subset}/${img.id}.jpg`
    const res = await fetch(url)
    if (!res.ok) throw new Error(`Download failed ${res.status} for ${url}`)
    await writeFile(original, Buffer.from(await res.arrayBuffer()))
  }
  const base = sharp(original).rotate()
  const { width, height } = await base.clone().toBuffer({ resolveWithObject: true }).then((r) => r.info)
  const stats = await base.clone().resize(32).stats()
  const { r, g, b } = stats.dominant
  for (const w of widths) {
    const target = Math.min(w, width)
    await base.clone().resize({ width: target }).webp({ quality: 74, effort: 6 }).toFile(join(outDir, `${img.slug}-${w}.webp`))
  }
  meta[img.slug] = {
    src: `/images/${img.slug}-960.webp`,
    srcSet: widths.map((w) => `/images/${img.slug}-${w}.webp ${Math.min(w, width)}w`).join(', '),
    width,
    height,
    focus: img.focus,
    alt: img.alt,
    tone: `#${toHex(r)}${toHex(g)}${toHex(b)}`,
    credit: { author: img.author, title: img.title, landing: img.landing, license: 'CC BY 2.0' },
  }
  console.log(`✓ ${img.slug} (${width}×${height})`)
}

const banner = '// Generated by scripts/prepare-images.mjs — do not edit by hand.\n'
await writeFile(
  join(root, 'src', 'data', 'images.generated.ts'),
  `${banner}export const images = ${JSON.stringify(meta, null, 2)} as const\n\nexport type ImageSlug = keyof typeof images\n`,
)
