// Generated by scripts/prepare-images.mjs — do not edit by hand.
export const images = {
  "book-pages": {
    "src": "/images/book-pages-960.webp",
    "srcSet": "/images/book-pages-160.webp 160w, /images/book-pages-320.webp 320w, /images/book-pages-640.webp 640w, /images/book-pages-960.webp 960w",
    "width": 1024,
    "height": 575,
    "focus": "45% 50%",
    "alt": "Close-up of a paperback's pages fanned on a table",
    "tone": "#f8f8f8",
    "credit": {
      "author": "' PaiO",
      "title": "Libro",
      "landing": "https://www.flickr.com/photos/bluefever/2547557832",
      "license": "CC BY 2.0"
    }
  },
  "reading-aloud": {
    "src": "/images/reading-aloud-960.webp",
    "srcSet": "/images/reading-aloud-160.webp 160w, /images/reading-aloud-320.webp 320w, /images/reading-aloud-640.webp 640w, /images/reading-aloud-960.webp 768w",
    "width": 768,
    "height": 1024,
    "focus": "50% 35%",
    "alt": "A person reading aloud from a book between tall bookshelves",
    "tone": "#887868",
    "credit": {
      "author": "Jim.landover3",
      "title": "me reading a book",
      "landing": "https://www.flickr.com/photos/jimlandover3/3657781806",
      "license": "CC BY 2.0"
    }
  },
  "reader-park": {
    "src": "/images/reader-park-960.webp",
    "srcSet": "/images/reader-park-160.webp 160w, /images/reader-park-320.webp 320w, /images/reader-park-640.webp 640w, /images/reader-park-960.webp 960w",
    "width": 1024,
    "height": 681,
    "focus": "62% 40%",
    "alt": "A person lying on the grass, absorbed in a paperback",
    "tone": "#182818",
    "credit": {
      "author": "Grant",
      "title": "reading politics",
      "landing": "https://www.flickr.com/photos/visual_dichotomy/4240056336",
      "license": "CC BY 2.0"
    }
  },
  "bookshop": {
    "src": "/images/bookshop-960.webp",
    "srcSet": "/images/bookshop-160.webp 160w, /images/bookshop-320.webp 320w, /images/bookshop-640.webp 640w, /images/bookshop-960.webp 960w",
    "width": 1024,
    "height": 768,
    "focus": "60% 45%",
    "alt": "A customer browsing tall wooden shelves in a second-hand bookshop",
    "tone": "#987858",
    "credit": {
      "author": "David Mellis",
      "title": "Last day in Davis square",
      "landing": "https://www.flickr.com/photos/mellis/2373450535",
      "license": "CC BY 2.0"
    }
  },
  "reading-group": {
    "src": "/images/reading-group-960.webp",
    "srcSet": "/images/reading-group-160.webp 160w, /images/reading-group-320.webp 320w, /images/reading-group-640.webp 640w, /images/reading-group-960.webp 960w",
    "width": 1024,
    "height": 683,
    "focus": "45% 55%",
    "alt": "Three adults leaning over open books together at a table",
    "tone": "#d8c8a8",
    "credit": {
      "author": "Ronnie Macdonald",
      "title": "Beijing 19",
      "landing": "https://www.flickr.com/photos/ronmacphotos/4941706006",
      "license": "CC BY 2.0"
    }
  },
  "potter-hands": {
    "src": "/images/potter-hands-960.webp",
    "srcSet": "/images/potter-hands-160.webp 160w, /images/potter-hands-320.webp 320w, /images/potter-hands-640.webp 640w, /images/potter-hands-960.webp 768w",
    "width": 768,
    "height": 1024,
    "focus": "50% 55%",
    "alt": "Hands shaping a clay vase on a potter's wheel",
    "tone": "#787878",
    "credit": {
      "author": "greckor",
      "title": "IMG_0459",
      "landing": "https://www.flickr.com/photos/gregcutler/1427768969",
      "license": "CC BY 2.0"
    }
  },
  "creator-desk": {
    "src": "/images/creator-desk-960.webp",
    "srcSet": "/images/creator-desk-160.webp 160w, /images/creator-desk-320.webp 320w, /images/creator-desk-640.webp 640w, /images/creator-desk-960.webp 960w",
    "width": 1024,
    "height": 768,
    "focus": "40% 55%",
    "alt": "A home desk set up with a studio microphone, monitor and lamp",
    "tone": "#080828",
    "credit": {
      "author": "Johan Larsson",
      "title": "Untitled",
      "landing": "https://www.flickr.com/photos/johanl/8289365270",
      "license": "CC BY 2.0"
    }
  },
  "indie-shop": {
    "src": "/images/indie-shop-960.webp",
    "srcSet": "/images/indie-shop-160.webp 160w, /images/indie-shop-320.webp 320w, /images/indie-shop-640.webp 640w, /images/indie-shop-960.webp 960w",
    "width": 1024,
    "height": 768,
    "focus": "50% 45%",
    "alt": "Colourful clothes and framed pictures on red walls in a small independent shop",
    "tone": "#080808",
    "credit": {
      "author": "Lindsey Nicholson",
      "title": "Vintage!",
      "landing": "https://www.flickr.com/photos/linznicholson/4361464257",
      "license": "CC BY 2.0"
    }
  },
  "craft-market": {
    "src": "/images/craft-market-960.webp",
    "srcSet": "/images/craft-market-160.webp 160w, /images/craft-market-320.webp 320w, /images/craft-market-640.webp 640w, /images/craft-market-960.webp 960w",
    "width": 1024,
    "height": 640,
    "focus": "50% 60%",
    "alt": "Handmade clay pots laid out at a craft market",
    "tone": "#785848",
    "credit": {
      "author": "LollyKnit",
      "title": "Thai Pottery",
      "landing": "https://www.flickr.com/photos/lollyknit/688514866",
      "license": "CC BY 2.0"
    }
  },
  "guitarist": {
    "src": "/images/guitarist-960.webp",
    "srcSet": "/images/guitarist-160.webp 160w, /images/guitarist-320.webp 320w, /images/guitarist-640.webp 640w, /images/guitarist-960.webp 681w",
    "width": 681,
    "height": 1024,
    "focus": "50% 35%",
    "alt": "A musician playing acoustic guitar at a microphone",
    "tone": "#180808",
    "credit": {
      "author": "Terry Johnston",
      "title": "Sound Check",
      "landing": "https://www.flickr.com/photos/powerbooktrance/457354973",
      "license": "CC BY 2.0"
    }
  },
  "home-studio": {
    "src": "/images/home-studio-960.webp",
    "srcSet": "/images/home-studio-160.webp 160w, /images/home-studio-320.webp 320w, /images/home-studio-640.webp 640w, /images/home-studio-960.webp 960w",
    "width": 1024,
    "height": 768,
    "focus": "55% 50%",
    "alt": "A home recording studio with keyboards, speakers and a laptop",
    "tone": "#080808",
    "credit": {
      "author": "bkRiverdog",
      "title": "Keys8",
      "landing": "https://www.flickr.com/photos/riverdog/16558260/",
      "license": "CC BY 2.0"
    }
  },
  "small-venue": {
    "src": "/images/small-venue-960.webp",
    "srcSet": "/images/small-venue-160.webp 160w, /images/small-venue-320.webp 320w, /images/small-venue-640.webp 640w, /images/small-venue-960.webp 960w",
    "width": 1024,
    "height": 768,
    "focus": "50% 55%",
    "alt": "An empty stage framed by red curtains",
    "tone": "#080808",
    "credit": {
      "author": "bfishadow",
      "title": "Red Stage",
      "landing": "https://www.flickr.com/photos/bfishadow/3144319914",
      "license": "CC BY 2.0"
    }
  },
  "gig-crowd": {
    "src": "/images/gig-crowd-960.webp",
    "srcSet": "/images/gig-crowd-160.webp 160w, /images/gig-crowd-320.webp 320w, /images/gig-crowd-640.webp 640w, /images/gig-crowd-960.webp 960w",
    "width": 1024,
    "height": 683,
    "focus": "60% 50%",
    "alt": "A crowd raising their hands under red stage light",
    "tone": "#280808",
    "credit": {
      "author": "Samuel Breen",
      "title": "Roses",
      "landing": "https://www.flickr.com/photos/52188855@N05/8021257866",
      "license": "CC BY 2.0"
    }
  },
  "phone-app": {
    "src": "/images/phone-app-960.webp",
    "srcSet": "/images/phone-app-160.webp 160w, /images/phone-app-320.webp 320w, /images/phone-app-640.webp 640w, /images/phone-app-960.webp 960w",
    "width": 1024,
    "height": 681,
    "focus": "60% 50%",
    "alt": "A hand holding a phone with an app open on screen",
    "tone": "#080808",
    "credit": {
      "author": "David Goehring",
      "title": "Doodle Jumper",
      "landing": "https://www.flickr.com/photos/carbonnyc/4581311847",
      "license": "CC BY 2.0"
    }
  },
  "tech-podcast": {
    "src": "/images/tech-podcast-960.webp",
    "srcSet": "/images/tech-podcast-160.webp 160w, /images/tech-podcast-320.webp 320w, /images/tech-podcast-640.webp 640w, /images/tech-podcast-960.webp 960w",
    "width": 1024,
    "height": 768,
    "focus": "40% 40%",
    "alt": "A presenter speaking into a microphone beside a laptop",
    "tone": "#d8d8d8",
    "credit": {
      "author": "Javier Leiva",
      "title": "Los Content Curators | Presentación del libro",
      "landing": "https://www.flickr.com/photos/catorze/11690374424",
      "license": "CC BY 2.0"
    }
  },
  "workshop": {
    "src": "/images/workshop-960.webp",
    "srcSet": "/images/workshop-160.webp 160w, /images/workshop-320.webp 320w, /images/workshop-640.webp 640w, /images/workshop-960.webp 960w",
    "width": 1024,
    "height": 743,
    "focus": "65% 35%",
    "alt": "An educator leading a workshop for a group seated with laptops",
    "tone": "#f8f8f8",
    "credit": {
      "author": "Eva Blue",
      "title": "spice corps montreal 2",
      "landing": "https://www.flickr.com/photos/evablue/5738800135",
      "license": "CC BY 2.0"
    }
  },
  "meetup": {
    "src": "/images/meetup-960.webp",
    "srcSet": "/images/meetup-160.webp 160w, /images/meetup-320.webp 320w, /images/meetup-640.webp 640w, /images/meetup-960.webp 960w",
    "width": 1024,
    "height": 683,
    "focus": "45% 75%",
    "alt": "Three people working together around a laptop",
    "tone": "#e8d8c8",
    "credit": {
      "author": "corinnepw",
      "title": "LadyHacks 2014",
      "landing": "https://www.flickr.com/photos/oh_you/13042451783",
      "license": "CC BY 2.0"
    }
  },
  "agency-meeting": {
    "src": "/images/agency-meeting-960.webp",
    "srcSet": "/images/agency-meeting-160.webp 160w, /images/agency-meeting-320.webp 320w, /images/agency-meeting-640.webp 640w, /images/agency-meeting-960.webp 960w",
    "width": 1024,
    "height": 683,
    "focus": "40% 60%",
    "alt": "People talking around a long table in a bright meeting room",
    "tone": "#986828",
    "credit": {
      "author": "P.O. Arnäs",
      "title": "Untitled",
      "landing": "https://www.flickr.com/photos/dr_po/8958641373/",
      "license": "CC BY 2.0"
    }
  }
} as const

export type ImageSlug = keyof typeof images
